import '../Model/product.dart';

List<Product> products = [
  Product(
    imagePaths: 'assets/images/boots/ACG+ZOOM+GAIADOME+GORETEX.png',
    description: 'ACG ZOOM GAIADOME GORETEX',
    price: '\$50',
    category: 'Boots',
    discount: '20% OFF',
  ),
  Product(
    imagePaths: 'assets/images/boots/LUNAR+FORCE+1+DUCKBOOT.png',
    description: 'LUNAR FORCE 1 DUCKBOOT',
    price: '\$70',
    category: 'Boots',
    discount: '20% OFF',
  ),
  Product(
    imagePaths: 'assets/images/boots/NIKE+CYGNAL.png',
    description: 'NIKE CYGNAL',
    price: '\$50',
    category: 'Boots',
    discount: '10% OFF',
  ),
  Product(
    imagePaths: 'assets/images/boots/NIKE+SFB+6_+NSW+LEATHER.png',
    description: 'NIKE+SFB+6_+NSW+LEATHER',
    price: '\$50',
    category: 'Boots',
    discount: '30% OFF',
  ),
  Product(
      imagePaths: 'assets/images/boots/NIKE+SFB+B1.jpeg',
      description: 'NIKE SFB B1',
      price: '\$50',
      category: 'Boots'),
  Product(
      imagePaths: 'assets/images/boots/NIKE+SFB+B2.png',
      description: 'NIKE SFB B2',
      price: '\$50',
      category: 'Boots'),
  Product(
    imagePaths: 'assets/images/boots/NIKE+SFB+B2+L.png',
    description: 'NIKE SFB B2 L',
    price: '\$50',
    category: 'Boots',
    discount: '07% OFF',
  ),
  Product(
      imagePaths: 'assets/images/boots/NIKE+SFB+B2+REALTREE.png',
      description: 'NIKE SFB B2 REALTREE',
      price: '\$50',
      category: 'Boots'),
  Product(
      imagePaths: 'assets/images/boots/NIKE+SFB+GEN+2+8.png',
      description: 'NIKE SFB GEN 2 8',
      price: '\$50',
      category: 'Boots'),
  Product(
    imagePaths: 'assets/images/boots/NIKE+WOODSIDE+II.png',
    description: 'NIKE WOODSIDE II',
    price: '\$50',
    category: 'Boots',
    discount: '30% OFF',
  ),
  Product(
      imagePaths: 'assets/images/Running/AIR+ZOOM+PEGASUS+41.png',
      description: 'AIR ZOOM PEGASUS 41',
      price: '\$110',
      category: 'Running'),
  Product(
      imagePaths: 'assets/images/Running/AIR+ZOOM+PEGASUS+41+(GS).png',
      description: 'AIR ZOOM PEGASUS 41 (GS)',
      price: '\$510',
      category: 'Running'),
  Product(
    imagePaths: 'assets/images/Running/NIKE+PEGASUS+TRAIL+5+(GS).png',
    description: 'NIKE PEGASUS TRAIL 5 (GS)',
    price: '\$800',
    category: 'Running',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Running/NIKE+PEGASUS+TRAIL+5+GTX.png',
    description: 'NIKE PEGASUS TRAIL 5 GTX',
    price: '\$1200',
    category: 'Running',
    discount: '10% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Running/NIKE+REACTX+INFINITY+RUN+4.png',
    description: 'NIKE REACTX INFINITY RUN 4',
    price: '\$80',
    category: 'Running',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Running/W+AIR+ZOOM+PEGASUS+41.png',
    description: 'W AIR ZOOM PEGASUS 41',
    price: '\$560',
    category: 'Running',
    discount: '5% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Running/ZOOMX+VAPORFLY+NEXT%+3+FK+PRM.png',
    description: 'ZOOMX VAPORFLY NEXT 3 FK PRM',
    price: '\$120',
    category: 'Running',
  ),
  Product(
    imagePaths: 'assets/images/Running/NIKE+REACTX+INFINITY+RUN+4.png',
    description: 'NIKE REACTX INFINITY RUN 4',
    price: '\$80',
    category: 'Running',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Running/W+AIR+ZOOM+PEGASUS+41.png',
    description: 'W AIR ZOOM PEGASUS 41',
    price: '\$560',
    category: 'Running',
    discount: '5% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/AIR+FORCE+1+07.png',
    description: 'AIR FORCE 1 07',
    price: '\$120',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/AIR+ZOOM+PEGASUS+41.png',
    description: 'AIR ZOOM PEGASUS 41',
    price: '\$140',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/KD17.png',
    description: 'KD17',
    price: '\$320',
    category: 'Sneakers',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+C1TY.png',
    description: 'NIKE C1TY',
    price: '\$1020',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+DUNK+LOW+RETRO+SE.png',
    description: 'NIKE DUNK LOW RETRO SE',
    price: '\$120',
    category: 'Sneakers',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+FREE+METCON+6.png',
    description: 'NIKE FREE METCON 6',
    price: '\$20',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+P-6000.png',
    description: 'NIKE P-6000',
    price: '\$820',
    category: 'Sneakers',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+REACTX+INFINITY+RUN+4.png',
    description: 'NIKE REACTX INFINITY RUN 4',
    price: '\$120',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/NIKE+ZOOM+VOMERO+5.png',
    description: 'NIKE ZOOM VOMERO 5',
    price: '\$320',
    category: 'Sneakers',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sneakers/ZOOMX+VAPORFLY+NEXT%+3+FK+PRM.png',
    description: 'ZOOMX VAPORFLY NEXT 3FK PRM',
    price: '\$320',
    category: 'Sneakers',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/AIR+FORCE+1+07.png',
    description: 'AIR FORCE 1 07',
    price: '\$120',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/AIR+FORCE+1+07+LV8.png',
    description: 'AIR FORCE 1 07 LV8',
    price: '\$420',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/AIR+MAX+DN.png',
    description: 'AIR MAX DN',
    price: '\$20',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+AIR+MAX+SC.png',
    description: 'NIKE AIR MAX SC',
    price: '\$120',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+C1TY.png',
    description: 'NIKE C1TY',
    price: '\$1020',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+DUNK+LOW+RETRO.png',
    description: 'NIKE DUNK LOW RETRO',
    price: '\$120',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+GATO.png',
    description: 'NIKE GATO',
    price: '\$120',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+P-6000.png',
    description: 'NIKE P-6000',
    price: '\$820',
    category: 'Fashion',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/NIKE+SHOX+R4.png',
    description: 'NIKE SHOX R4',
    price: '\$120',
    category: 'Fashion',
    discount: '20% OFF',
  ),
  Product(
    imagePaths: 'assets/images/Fashion/W+NIKE+AL8.png',
    description: 'W NIKE AL8',
    price: '\$120',
    category: 'Fashion',
    discount: '60% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/AIR+JORDAN+MULE.png',
    description: 'AIR JORDAN MULE',
    price: '\$420',
    category: 'Sandals',
  ),
  Product(
    imagePaths: 'assets/images/sandals/NIKE+BURROW+NA.png',
    description: 'NIKE BURROW NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/NIKE+CALM+MULE+NA.png',
    description: 'NIKE CALM MULE NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/NIKE+CALM+SLIDE.png',
    description: 'NIKE CALM SLIDE',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/W+NIKE+BURROW+SE+NA.png',
    description: 'W NIKE BURROW SE NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/W+NIKE+CALM+MULE+NA.png',
    description: 'W NIKE CALM MULE NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/W+NIKE+CALM+MULE+SE+NA.png',
    description: 'W NIKE CALM MULE SE NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/W+NIKE+CALM+SLIDE.png',
    description: 'W NIKE CALM SLIDE',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/W+NIKE+VICTORI+ONE+SLIDE.png',
    description: 'W NIKE VICTORI ONE SLIDE',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
  Product(
    imagePaths: 'assets/images/sandals/WMNS+NIKE+BURROW+NA.png',
    description: 'WMNS NIKE BURROW NA',
    price: '\$120',
    category: 'Sandals',
    discount: '30% OFF',
  ),
];
